#!/bin/bash

echo
echo "===================================="
echo "Installing awesome-wm"
echo "===================================="
# was build-dep?
sudo apt-get install \
              autoconf automake libtool gperf xmlto \
              lua5.2 gir1.2-pango-1.0 \
              libxcb-util0-dev libxcb1-dev libxcb-randr0-dev \
              libxcb-xinerama0-dev libxcb-xtest0-dev libxcb-shape0-dev \
              libglib2.0-dev libstartup-notification0-dev libxcb-icccm4-dev \
              libxcb-keysyms1-dev \
              libx11-xcb-dev \
              imagemagick libxdg-basedir-dev \
              libcairo2-dev libxcb-image0-dev \
              libxcursor-dev libgdk-pixbuf2.0-dev \
              liblua5.2-dev \
              lua5.1 liblua5.1-0-dev \
              libdbus-1-dev \
              asciidoc

#sudo apt-get install awesome awesome-extra // install from git for 3.5

echo
echo "===================================="
echo "Fixing awesome startup bug"
echo "===================================="
# cd /usr/share/xsessions/
# sudo cp awesome.desktop awesome.desktop.BK
# sed 's/NoDisplay=true/#NoDisplay=true/g' awesome.desktop.BK | sudo tee awesome.desktop

