#!/bin/bash

# move to home
cd ~

# bin
echo "## bin"
if [ -d bin ]
then
  echo "~/bin folder already exists. Check its contents."
fi
ln -f -s git/dotfiles/bin bin

# git
echo "## git"
rm .gitconfig
ln -f -s git/dotfiles/git/gitconfig .gitconfig

# zsh
echo "## zsh"
rm .zshrc .bash_aliases
ln -f -s git/dotfiles/zsh/zshrc .zshrc
ln -f -s git/dotfiles/zsh/aliases .bash_aliases
if [ ! -d git/oh-my-zsh ]
then
  git clone git@github.com:robbyrussell/oh-my-zsh.git git/oh-my-zsh
fi
ln -f -s git/oh-my-zsh .oh-my-zsh

# vim
echo "## vim"
rm -r .vim .vimrc
ln -f -s git/dotfiles/vim/vimrc .vimrc
ln -f -s git/dotfiles/vim .vim
if [ ! -d .vim/bundle/vundle ]
then
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi
vim +BundleInstall +qall!

if [ -f ycm_core.so ]
then
  cd .vim/bundle/YouCompleteMe
  ./install.sh --clang-completer
  cd -
fi

# tmux
echo "## tmux"
rm -r .tmux.conf
ln -f -s git/dotfiles/tmux/tmux.conf .tmux.conf
