#!/bin/bash

# move to home
cd ~

# zsh
cp .zshrc .zshrc.BK
cp .bash_aliases .bash_aliases.BK
ln -f -s git/dotfiles/zsh/zshrc .zshrc
ln -f -s git/dotfiles/zsh/aliases .bash_aliases

# vim
cp -r .vim .vim.BK
cp .vimrc .vimrc.BK
ln -f -s git/dotfiles/vim .vim
ln -f -s git/dotfiles/vim/vimrc .vimrc
