#!/bin/bash

# move to home
cd ~

# zsh
rm .zshrc .bash_aliases
ln -f -s git/dotfiles/zsh/zshrc .zshrc
ln -f -s git/dotfiles/zsh/aliases .bash_aliases
git clone git@github.com:robbyrussell/oh-my-zsh.git git/oh-my-zsh
ln -f -s git/oh-my-zsh .oh-my-zsh

# vim
rm -r .vim .vimrc
ln -f -s git/dotfiles/vim/vimrc .vimrc
ln -f -s git/dotfiles/vim .vim
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim +BundleInstall +qall!

if [ -f ycm_core.so ]; then
  cd .vim/bundle/YouCompleteMe
  ./install.sh --clang-completer
  cd -
fi

# tmux
rm -r .tmux.conf
ln -f -s git/dotfiles/tmux/tmux.conf .tmux.conf
