# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"
#DEFAULT_USER="bais"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# BAIS - bin in path
homebin="$HOME/bin"
if [[ -d $homebin && ! ":$PATH:" == *":$homebin:"* ]]
then
  export PATH="$PATH:$homebin"
fi

# BAIS - git/mlr/share/bin in path
mlrbin="$HOME/git/mlr/share/bin"
if [[ -d $mlrbin && ! ":$PATH:" == *":$mlrbin:"* ]]
then
  export PATH="$PATH:$mlrbin"
fi

mlrgdbaddons="$HOME/git/mlr/tools/gdb-addons"
if [[ -d $mlrgdbaddons && ! ":$PATH:" == *":$mlrgdbaddons:"* ]]
then
  export PATH="$PATH:$mlrgdbaddons"
fi

# BAIS - aliases
source ~/.bash_aliases

# BAIS - keyboard layout options
setxkbmap -option 'grp:shifts_toggle' 'it,de'

# BAIS - Completion for ..
zstyle ':completion:*' special-dirs true

# BAIS - vi key bindings
bindkey -v
# BAIS - fixes certain key bindings to adhere to vim
bindkey "^?" backward-delete-char
bindkey "^W" backward-kill-word
bindkey "^H" backward-delete-char
bindkey "^U" kill-line

# BAIS - xterm colors for vim solarized colorscheme
#[ -z "$TMUX" ] && export TERM="xterm-256color"
export TERM="xterm-256color"

export SVN_EDITOR="vim"
ulimit -c unlimited

# BAIS - update fpath for completion scripts
fpath=(~/bin/completion/ $fpath)
autoload -U compinit
compinit
zstyle ':completion:*' menu select=2
zstyle ":completion:*:descriptions" format "%B%d%b"

# BAIS - MLR ENV VARIABLES
export MLR_EDITOR_CMD='vim <fname>'

# BAIS - ROS setup

ros_file='/opt/ros/hydro/setup.zsh'
[ -f $ros_file ] && source $ros_file
