# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"
#DEFAULT_USER="bais"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# BAIS - bin in path
if [ -d "$HOME/bin" ]
then
  export PATH="$PATH:$HOME/bin"
fi

# BAIS - adjust brightness
#function sb() {
#  local d
#  case $1 in
#    up)
#      d=5
#      ;;
#    down)
#      d=-5
#      ;;
#    *)
#      echo "Option must be [ up | down ]."
#      return 1
#      ;;
#  esac
#  
#  local curr=$(cat /sys/class/backlight/acpi_video0/brightness)
#  local new=$(( $curr + $d ))
#
#  if [[ $new -gt 100 ]] then
#    new=100
#  elif [[ $new -lt 0 ]] then
#    new=0
#  fi
#
#  echo $(( $curr + $d )) > /sys/class/backlight/acpi_video0/brightness
#}
