# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"
# ZSH_THEME="powerline"
export TERM="xterm-256color"
# export TERM="screen-256color"
# DEFAULT_USER="bais"
POWERLINE_RIGHT_B="none"
POWERLINE_RIGHT_A="exit-status-on-fail"
POWERLINE_NO_BLANK_LINE="true"
POWERLINE_PATH="short"
POWERLINE_DETECT_SSH="true"
# fixes right prompt extra space issue
ZLE_RPROMPT_INDENT=0

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# BAIS - hist size
# export HISTFILESIZE=
# export HISTSIZE=

# BAIS - PATH extentions
export LD_LIBRARY_PATH="/home/bais/git/mlr/share/lib:$LD_LIBRARY_PATH"
# export PATH="/home/bais/.local/bin:$PATH"
export PATH="/home/bais/bin:$PATH"
export PATH="/home/bais/bin_extern:$PATH"
export PATH="/home/bais/git/mlr/share/bin:$PATH"
export PATH="/home/lib/bin:$PATH"
export PATH="/home/bais/git/mlr/tools/gdb-addons:$PATH"
export PATH="/home/bais/git/tmuxifier/bin:$PATH"
eval "$(tmuxifier init -)"
export PATH="/home/bais/anaconda2/bin:$PATH"  # added by Anaconda2 4.0.0 installer
export PKG_CONFIG_PATH="/usr/local/lib64/pkgconfig:$PKG_CONFIG_PATH"  # libfreenect

# BAIS - aliases
source ~/.bash_aliases

# BAIS - keyboard layout options
setxkbmap -option 'grp:shifts_toggle' 'it,de'

# BAIS - Completion for ..
zstyle ':completion:*' special-dirs true

# BAIS - vi key bindings
bindkey -v
# BAIS - fixes certain key bindings to adhere to vim
bindkey "^?" backward-delete-char
bindkey "^W" backward-kill-word
bindkey "^H" backward-delete-char
bindkey "^U" kill-line

export SVN_EDITOR="vim"
ulimit -c unlimited

# BAIS - update fpath for completion scripts
fpath=(~/bin/completion/ $fpath)
autoload -U compinit
compinit
zstyle ':completion:*' menu select=2
zstyle ":completion:*:descriptions" format "%B%d%b"

# BAIS - MLR ENV VARIABLES
# export MLR_PATH='~/git/mlr'
# export MLR_EDITOR_CMD='vim <fname>'

# # BAIS - ROS setup
# export ROS_VERSION="indigo"
# export ROS_MASTER_URI="http://$HOST:11311"
# export ROS_HOSTNAME="$HOST"
# # export ROS_IP=$(hostname -I | awk '{print $(1)}')

# BAIS location of the dotfiles folder
export DOTFILES_DIR=/home/bais/git/dotfiles

# BAIS - editor env
export EDITOR=vim

# BAIS - env variable for website scripts
export IPVS=ipvs

# BAIS - tex uses manually installed packages
# export TEXINPUTS=$HOME/latex/pgfplots/tex//:

export PNEUMATICBOX_IP="cookiemonster.local"

# BAIS - default GPG key
export GPGKEY=AF34AF73

# source venv


# BAIS - bash completion script compatibility mode
autoload bashcompinit
bashcompinit

# BAIS - conda autocomplete feature
eval "$(register-python-argcomplete conda)"

# export PYTHONNOUSERSITE=1

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk
export PATH=$PATH:/usr/jvm/java-7-openjdk/bin

export PATH=$PATH:$HOME/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin

# BAIS - remove suplicates from path
if [ -n "$PATH" ]; then
  old_PATH=$PATH:; PATH=
  while [ -n "$old_PATH" ]; do
    x=${old_PATH%%:*}       # the first remaining entry
    case $PATH: in
      *:"$x":*) ;;         # already there
      *) PATH=$PATH:$x;;    # not there yet
    esac
    old_PATH=${old_PATH#*:}
  done
  export PATH=${PATH#:}
  unset old_PATH x
fi
